### PR TITLE
Index updated as per #3

### PR DESCRIPTION
**Pull request by PaulSoumik**
Index page update issue #3

### CODE REVIEW

**Comment by ZER-0-NE** [comment]
@PaulSoumik is this the PR about the countdown timer?

**Comment by PaulSoumik** [comment]
yes it is and that speakers section change

**Comment by ZER-0-NE** [comment]
Screenshot from 2019-12-26 17-49-04
@PaulSoumik I checked out your PR locally, I cannot see the speakers section. Can you attach a proper SS so that I can merge accordingly?
Also, add an SS for the timer.
@biparnakroy @mpalrocks please check the screenshots and see if they would be a good fit in the website.

**Comment by PaulSoumik** [comment]
https://paulsoumik.github.io/web/.

**Comment by ZER-0-NE** [comment]
Great job @PaulSoumik .
One suggestion though, can you update the code to show the countdown timer in all the slides rather than just the first one?
Also please get in touch with @monsij and update the registration part as he has made here: https://monsij.github.io/web/

Keep the rest same, and just update the registration part from monsij's work. I expect you to send the PR by tomorrow. Sounds good?

**Pull request closed without merging**
